import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require('playwright');
const url = 'file://' + new URL('../deck-deal.html', import.meta.url).pathname;
const browser = await chromium.launch({ executablePath: (process.env.CHROMIUM || '/opt/pw-browsers/chromium'), args: ['--no-sandbox'] });
const errs = [];
async function session(scheme, tag) {
  const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, colorScheme: scheme });
  const p = await ctx.newPage();
  p.on('pageerror', e => errs.push(tag + ' pageerror: ' + e.message));
  p.on('console', m => { if (m.type() === 'error' && !/fonts\.g|ERR_|Failed to load resource/.test(m.text())) errs.push(tag + ' console: ' + m.text()); });
  await p.goto(url); await p.waitForTimeout(700);
  const ovf = async (n) => { const o = await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]); if (o[0] > o[1]) errs.push(`${tag} overflow-x @${n}: ${o}`); };
  await p.screenshot({ path: `shots/${tag}-1-vide.png` }); await ovf('vide');
  await p.click('#btnSample'); await p.waitForTimeout(400);
  await p.screenshot({ path: `shots/${tag}-2-saisie.png` }); await ovf('saisie');
  await p.screenshot({ path: `shots/${tag}-2b-saisie-full.png`, fullPage: true });
  await p.click('#btnRun'); await p.waitForTimeout(900);
  await p.screenshot({ path: `shots/${tag}-3-progression.png` });
  await p.waitForFunction(() => /terminée/.test(document.querySelector('#progTitle').textContent), null, { timeout: 90000 });
  await p.waitForTimeout(1500);
  await p.screenshot({ path: `shots/${tag}-4-resultats.png` }); await ovf('resultats');
  await p.screenshot({ path: `shots/${tag}-4b-resultats-full.png`, fullPage: true });
  await p.click('#segDeliv button:nth-of-type(2), #segDeliv [role=radio]:nth-of-type(2)'); await p.waitForTimeout(900);
  await p.screenshot({ path: `shots/${tag}-5-direct.png` });
  await p.click('#segTab button:nth-of-type(2), #segTab [role=radio]:nth-of-type(2)'); await p.waitForTimeout(700);
  await p.screenshot({ path: `shots/${tag}-6-vendeurs.png` }); await ovf('vendeurs');
  await p.click('#segTab button:nth-of-type(1), #segTab [role=radio]:nth-of-type(1)'); await p.waitForTimeout(500);
  await p.click('#list .row:not(.is-missing)'); await p.waitForTimeout(900);
  await p.screenshot({ path: `shots/${tag}-7-carte.png` }); await ovf('carte');
  await p.keyboard.press('Escape'); await p.waitForTimeout(600);
  await p.click('#btnCart'); await p.waitForTimeout(900);
  await p.screenshot({ path: `shots/${tag}-8-panier.png` });
  await p.keyboard.press('Escape'); await p.waitForTimeout(600);
  await p.click('#btnSettings'); await p.waitForTimeout(900);
  await p.screenshot({ path: `shots/${tag}-9-reglages.png` });
  await ctx.close();
}
await session('light', 'L');
await session('dark', 'D');
await browser.close();
console.log(errs.length ? errs.join('\n') : 'no errors');
